// https://projecteuler.net/problem=2
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

function fibonacci(number) {
  if (number <= 1) { return number; }
  else {
    return fibonacci(number-1) + fibonacci(number-2);
  }  
}

const maxValue = 4000000;
let fibStart = 0;
let fibRow = [];
let fibResult = 0;
while (fibResult < maxValue) {
  fibStart += 1;
  fibResult = fibonacci(fibStart);
  if (fibResult < maxValue) {
    fibRow.push(fibResult);
  }
}
console.log(fibStart, fibResult, fibRow);

const sum = fibRow.filter((el) => { if (el%2==0) return el; }).reduce((acc, el) => { return acc + el; });  
console.log(sum);

